import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import {
  MicrophoneIcon,
  SearchIcon,
  UserCircleIcon,
} from "@heroicons/react/outline";
import { useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();
  function handleSearch(e) {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    router.push(`/search?term=${term}`);
  }

  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between p-5 text-sm text-gray-700 w-full">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        <div className="flex space-x-4 items-center">
          <p className="link">Image</p>
          <p className="link">Gmail</p>

          {/* <Avatar url="" /> */}
          <UserCircleIcon className="h-10" />
        </div>
      </header>

      <form className="flex flex-col mt-44 items-center flex-grow w-full ">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
          alt="google Image"
        />
        <div className="flex hover:shadow-lg mt-4 focus-within:shadow-lg max-w-xl px-5 py-3 items-center rounded-full sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-2 text-gray-700" />
          <input
            ref={searchInputRef}
            type="text"
            className=" flex-grow focus:outline-none "
          />
          <MicrophoneIcon className="h-5 text-gray-700  " />
        </div>
        <div className="flex w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn" onClick={handleSearch}>
            Google Search
          </button>
          <button className="btn" onClick={handleSearch}>
            Feeling lucky
          </button>
        </div>
      </form>
    </div>
  );
}
